### ISSUE TITLE
Not able to load the pretrained models network and weights mismatch 

### ISSUE THREAD

**Issue by hichem-abdellali** [lh9171338/ULSD-ISPRS#3]
Hi,

I am traying to run the inference code on some images but I am facing a problem loading the wights 

RuntimeError: Error(s) in loading state_dict for LCNN:
	Missing key(s) in state_dict: "extractor.down.0.weight", "extractor.down.0.bias", "extractor.down.1.weight", "extractor.down.1.bias", "extractor.down.1.running_mean", "extractor.down.1.running_var", "extractor.down.3.bn.weight", "extractor.down.3.bn.bias", "extractor.down.3.bn.running_mean", "extractor.down.3.bn.running_var", "extractor.down.3.conv1.weight", "extractor.down.3.conv1.bias", "extractor.down.3.bn1.weight", "extractor.down.3.bn1.bias", "extractor.down.3.bn1.running_mean", "extractor.down.3.bn1.running_var", "......
	Unexpected key(s) in state_dict: "model", "optimizer".

**Comment by lh9171338** [comment]
You can refer to the following code to load state_ dict：
```python
# Load model
  model = ULSD(cfg).to(device)
  model_filename = os.path.join(cfg.model_path, cfg.model_name)
  checkpoint = torch.load(model_filename, map_location=device)
  if 'model' in checkpoint.keys():
      state_dict = checkpoint['model'] # checkpoint contains 'model' and 'optimizer'
  else:
      state_dict = checkpoint
  model.load_state_dict(state_dict)
```

**Comment by hichem-abdellali** [comment]
Hi, 

This didn't solve the problem, I am trying to make the mixed version work

self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ULSD:
	size mismatch for lpn.lambda_: copying a param with shape torch.Size([2, 5]) from checkpoint, the shape in current model is torch.Size([2, 2]).
	size mismatch for lpn.head.heads.5.head.3.weight: copying a param with shape torch.Size([8, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([4, 64, 3, 3]).
	size mismatch for lpn.head.heads.5.head.3.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([4]).
	size mismatch for head.loi.lambda_: copying a param with shape torch.Size([32, 5]) from checkpoint, the shape in current model is torch.Size([32, 2]).
python-BaseException

**Comment by lh9171338** [comment]
You need to add the argument '--order 4' or '-o 4' after 'python test.py'

**Comment by hichem-abdellali** [comment]
It is working now, Thank you
